# Test config file for Blip
module:
  module_name:  'production_pointnet_DR'
  module_type:  'ml'
  module_mode:  'training'
  gpu:          True
  gpu_device:   0

dataset:
  # If this is the first time processing the simulation output
  process_simulation: True
  simulation_folder:  "/home/ncarrara/physics/DUNE/BlipModels/protodune/data/"
  simulation_files:   [
    "single_gammas_0.8378MeV_2232566.0.root",
    "single_gammas_0.8378MeV_2232566.1.root",
    "single_gammas_0.8378MeV_2232566.2.root",
    "single_gammas_0.8378MeV_2232566.3.root",
    "single_gammas_0.8378MeV_2232566.4.root",
    "single_gammas_2.566MeV_62973335.0.root",
    "single_gammas_2.566MeV_62973335.1.root",
    "single_gammas_2.566MeV_62973335.2.root",
    "single_gammas_3.365MeV_69967879.0.root",
    "single_gammas_3.365MeV_69967879.1.root",
    "single_gammas_3.365MeV_69967879.2.root",
    "single_gammas_3.365MeV_69967879.3.root",
    "single_gammas_3.365MeV_69967879.4.root",
    "single_gammas_4.745MeV_69938451.0.root",
    "single_gammas_4.745MeV_69938451.1.root",
    "single_gammas_4.745MeV_69938451.2.root",
    "single_gammas_4.745MeV_69938451.3.root",
    "single_gammas_4.745MeV_69938451.4.root",
    # "pnsNeutrons_output_sim_file_69883239.0.root",
    # #"pnsNeutrons_output_sim_file_69883239.1.root",
    # "pnsNeutrons_output_sim_file_69883239.2.root",
    # "pnsNeutrons_output_sim_file_69883239.3.root",
    # "pnsNeutrons_output_sim_file_69883239.4.root",
    # "pnsNeutrons_output_sim_file_69883239.5.root",
    # "pnsNeutrons_output_sim_file_69883239.6.root",
    # "pnsNeutrons_output_sim_file_69883239.7.root",
    # "pnsNeutrons_output_sim_file_69883239.8.root",
    # "pnsNeutrons_output_sim_file_69883239.9.root",
    # "pnsNeutrons_output_sim_file_69883239.10.root",
    # "pnsNeutrons_output_sim_file_69883239.11.root",
    # "pnsNeutrons_output_sim_file_69883239.12.root",
    # "pnsNeutrons_output_sim_file_69883239.13.root",
    # "pnsNeutrons_output_sim_file_69883239.14.root",
    # "pnsNeutrons_output_sim_file_69883239.15.root",
    # "pnsNeutrons_output_sim_file_69883239.16.root",
    # "pnsNeutrons_output_sim_file_69883239.17.root",
    # "pnsNeutrons_output_sim_file_69883239.18.root",
    # # "pnsNeutrons_output_sim_file_69883239.19.root",
    # "pnsNeutrons_output_sim_file_69883239.20.root",
    # "pnsNeutrons_output_sim_file_69883239.21.root",
    # "pnsNeutrons_output_sim_file_69883239.22.root",
    # # "pnsNeutrons_output_sim_file_69883239.23.root",
    # "pnsNeutrons_output_sim_file_69883239.24.root",
    # # "pnsNeutrons_output_sim_file_69883239.25.root",
    # # "pnsNeutrons_output_sim_file_69883239.26.root",
    # "pnsNeutrons_output_sim_file_69883239.27.root",
    # "pnsNeutrons_output_sim_file_69883239.28.root",
    # "pnsNeutrons_output_sim_file_69883239.29.root",
    # "pnsNeutrons_output_sim_file_69883239.30.root",
    # "pnsNeutrons_output_sim_file_69883239.31.root",
    # "pnsNeutrons_output_sim_file_69883239.32.root",
    # "pnsNeutrons_output_sim_file_69883239.33.root",
    # "pnsNeutrons_output_sim_file_69883239.34.root",
    # "pnsNeutrons_output_sim_file_69883239.35.root",
    # # "pnsNeutrons_output_sim_file_69883239.36.root",
    # "pnsNeutrons_output_sim_file_69883239.37.root",
    # "pnsNeutrons_output_sim_file_69883239.38.root",
    # "pnsNeutrons_output_sim_file_69883239.39.root",
    # "pnsNeutrons_output_sim_file_69883239.40.root",
    # "pnsNeutrons_output_sim_file_69883239.41.root",
    # "pnsNeutrons_output_sim_file_69883239.42.root",
    # "pnsNeutrons_output_sim_file_69883239.43.root",
    # "pnsNeutrons_output_sim_file_69883239.44.root",
    # # "pnsNeutrons_output_sim_file_69883239.45.root",
    # "pnsNeutrons_output_sim_file_69883239.46.root",
    # # "pnsNeutrons_output_sim_file_69883239.47.root",
    # "pnsNeutrons_output_sim_file_69883239.48.root",
    # "pnsNeutrons_output_sim_file_69883239.49.root",
  ]

  # Otherwise, we want to just load the resulting data
  dataset_type:   "cluster"
  dataset_folder: "/home/ncarrara/physics/DUNE/BlipModels/protodune/data/"
  dataset_files:  [
    "single_gammas_0.8378MeV_2232566.0/view2_tpc2.npz",
    "single_gammas_0.8378MeV_2232566.1/view2_tpc2.npz",
    "single_gammas_0.8378MeV_2232566.2/view2_tpc2.npz",
    "single_gammas_0.8378MeV_2232566.3/view2_tpc2.npz",
    "single_gammas_0.8378MeV_2232566.4/view2_tpc2.npz",
    "single_gammas_2.566MeV_62973335.0/view2_tpc2.npz",
    "single_gammas_2.566MeV_62973335.1/view2_tpc2.npz",
    "single_gammas_2.566MeV_62973335.2/view2_tpc2.npz",
    "single_gammas_3.365MeV_69967879.0/view2_tpc2.npz",
    "single_gammas_3.365MeV_69967879.1/view2_tpc2.npz",
    "single_gammas_3.365MeV_69967879.2/view2_tpc2.npz",
    "single_gammas_3.365MeV_69967879.3/view2_tpc2.npz",
    "single_gammas_3.365MeV_69967879.4/view2_tpc2.npz",
    "single_gammas_4.745MeV_69938451.0/view2_tpc2.npz",
    "single_gammas_4.745MeV_69938451.1/view2_tpc2.npz",
    "single_gammas_4.745MeV_69938451.2/view2_tpc2.npz",
    "single_gammas_4.745MeV_69938451.3/view2_tpc2.npz",
    "single_gammas_4.745MeV_69938451.4/view2_tpc2.npz",
    #"pnsNeutrons_output_sim_file_69883239.0/view2_tpc2.npz",
    #"pnsNeutrons_output_sim_file_69883239.1/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.2/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.3/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.4/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.5/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.6/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.7/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.8/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.9/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.10/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.11/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.12/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.13/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.14/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.15/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.16/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.17/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.18/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.19/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.20/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.21/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.22/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.23/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.24/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.25/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.26/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.27/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.28/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.29/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.30/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.31/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.32/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.33/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.34/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.35/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.36/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.37/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.38/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.39/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.40/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.41/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.42/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.43/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.44/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.45/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.46/view2_tpc2.npz",
    # # "pnsNeutrons_output_sim_file_69883239.47/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.48/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.49/view2_tpc2.npz",
  ]
  normalized:     False
  root:           "."
  skip_processing:  False
  transform:      null
  pre_transform:  null
  pre_filter:     null

  # ---- variables ----
  positions:  ["channel", "tdc", "adc"]
  features:   []
  classes:    ["particle"]
  labels:     [
    [ 
      "capture_gamma_474", 
      "capture_gamma_336",
      "capture_gamma_256",
      #"capture_gamma_118",
      "capture_gamma_083",
      # "capture_gamma_051",
      # "capture_gamma_016",
      # "ar39",
      # "ar42",
      # "kr85",
      # "rn222",
      # "nuclear_recoil",
      # "electron_recoil"
    ]
  ]
  clusters:   ["particle"]

  # ---- normalization ----
  position_normalization:   []
  features_normalization:   []

  # ---- weights ----
  class_weights:  []
  sample_weights: []

  # clustering related parameters
  dbscan_min_samples: 6
  dbscan_eps:         39.0
  cluster_positions:  ["channel", "tdc"]

  # We only want to cluster shapes which are blips
  classes_mask: ["shape"]
  labels_mask:  [["blip"]]
  consolidate_classes:

loader:
  batch_size:       16
  test_split:       0.1
  test_seed:        100
  validation_split: 0.2
  validation_seed:  101
  num_workers:      4
  sparse:           True

training:
  epochs:       
  checkpoint:   10
  progress_bar: 'all'   # train, validation, test, all
  rewrite_bar:  False   # wether to leave bars after each epoch
  save_predictions: True  # wether to save network outputs in original file
  no_timing:  False     # wether to keep timing/memory info in callback
  seed:       42

model:
  # uncomment the line below and specify the model to load from a checkpoint.
  # load_model:   ".checkpoints/checkpoint_200.ckpt"

  # multiple options for model_type: 
  # [ "single", "composite", ... ]
  model_type: "single"
  PointNet: 
    input_dimension:      3
    classifications:      ["particle"]
    augmentations:
      jitter: 0.03
      flip:
        positions:     [0, 1]
        probabilities: [0.5, 0.5]
      shear:  0.2
    number_of_augmentations:  5
    embedding_type:       "dynamic_edge_conv"
    number_of_embeddings: 4
    number_of_neighbors:  [5, 10, 20, 30]    
    aggregation:          ["max", "max", "max", "max"]
    embedding_mlp_layers: [
      [5, 10, 25, 10],
      [10, 25, 50, 25],
      [20, 30, 40, 30],
      [30, 50, 75, 50]
    ]
    linear_output:        128
    mlp_output_layers:    [128, 256, 32]
    out_channels:         [4]
  
criterion:
  MultiClassProbabilityLoss:
    alpha:    1.0
    classes:  ["particle"]
  NTXEntropyLoss:
    alpha:  1.0
    classes:  ["reductions"]
    
metrics:
  ConfusionMatrixMetric:
    mode:   "cluster"
    inputs: ["particle"]
    number_of_classes: [4]
    consolidate_classes:

callbacks:
  LossCallback:
  ConfusionMatrixCallback:
    sig_acceptance: [0.1, 0.5, 0.9]

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9