# Test config file for Blip
module:
  module_name:  'production_unet_DR'
  module_type:  'ml'
  module_mode:  'training'
  gpu:          True
  gpu_device:   0

dataset:
  # If this is the first time processing the simulation output
  process_simulation: False
  simulation_folder:  "/home/ncarrara/physics/DUNE/BlipModels/protodune/data/"
  simulation_files:   [
    "pnsNeutrons_output_sim_file_69883239.0.root",
    #"pnsNeutrons_output_sim_file_69883239.1.root",
    "pnsNeutrons_output_sim_file_69883239.2.root",
    "pnsNeutrons_output_sim_file_69883239.3.root",
    "pnsNeutrons_output_sim_file_69883239.4.root",
    "pnsNeutrons_output_sim_file_69883239.5.root",
    "pnsNeutrons_output_sim_file_69883239.6.root",
    "pnsNeutrons_output_sim_file_69883239.7.root",
    "pnsNeutrons_output_sim_file_69883239.8.root",
    "pnsNeutrons_output_sim_file_69883239.9.root",
    "pnsNeutrons_output_sim_file_69883239.10.root",
    "pnsNeutrons_output_sim_file_69883239.11.root",
    "pnsNeutrons_output_sim_file_69883239.12.root",
    "pnsNeutrons_output_sim_file_69883239.13.root",
    "pnsNeutrons_output_sim_file_69883239.14.root",
    "pnsNeutrons_output_sim_file_69883239.15.root",
    "pnsNeutrons_output_sim_file_69883239.16.root",
    "pnsNeutrons_output_sim_file_69883239.17.root",
    "pnsNeutrons_output_sim_file_69883239.18.root",
    # "pnsNeutrons_output_sim_file_69883239.19.root",
    "pnsNeutrons_output_sim_file_69883239.20.root",
    "pnsNeutrons_output_sim_file_69883239.21.root",
    "pnsNeutrons_output_sim_file_69883239.22.root",
    # "pnsNeutrons_output_sim_file_69883239.23.root",
    "pnsNeutrons_output_sim_file_69883239.24.root",
    # "pnsNeutrons_output_sim_file_69883239.25.root",
    # "pnsNeutrons_output_sim_file_69883239.26.root",
    "pnsNeutrons_output_sim_file_69883239.27.root",
    "pnsNeutrons_output_sim_file_69883239.28.root",
    "pnsNeutrons_output_sim_file_69883239.29.root",
    "pnsNeutrons_output_sim_file_69883239.30.root",
    "pnsNeutrons_output_sim_file_69883239.31.root",
    "pnsNeutrons_output_sim_file_69883239.32.root",
    "pnsNeutrons_output_sim_file_69883239.33.root",
    "pnsNeutrons_output_sim_file_69883239.34.root",
    "pnsNeutrons_output_sim_file_69883239.35.root",
    # "pnsNeutrons_output_sim_file_69883239.36.root",
    "pnsNeutrons_output_sim_file_69883239.37.root",
    "pnsNeutrons_output_sim_file_69883239.38.root",
    "pnsNeutrons_output_sim_file_69883239.39.root",
    "pnsNeutrons_output_sim_file_69883239.40.root",
    "pnsNeutrons_output_sim_file_69883239.41.root",
    "pnsNeutrons_output_sim_file_69883239.42.root",
    "pnsNeutrons_output_sim_file_69883239.43.root",
    "pnsNeutrons_output_sim_file_69883239.44.root",
    # "pnsNeutrons_output_sim_file_69883239.45.root",
    "pnsNeutrons_output_sim_file_69883239.46.root",
    # "pnsNeutrons_output_sim_file_69883239.47.root",
    "pnsNeutrons_output_sim_file_69883239.48.root",
    "pnsNeutrons_output_sim_file_69883239.49.root",
  ]

  # Otherwise, we want to just load the resulting data
  dataset_type:   "voxel"
  dataset_folder: "/home/ncarrara/physics/DUNE/BlipModels/protodune/data/"
  dataset_files:  [
    "pnsNeutrons_output_sim_file_69883239.0/view2_tpc2.npz",
    #"pnsNeutrons_output_sim_file_69883239.1/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.2/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.3/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.4/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.5/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.6/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.7/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.8/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.9/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.10/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.11/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.12/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.13/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.14/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.15/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.16/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.17/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.18/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.19/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.20/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.21/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.22/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.23/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.24/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.25/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.26/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.27/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.28/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.29/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.30/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.31/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.32/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.33/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.34/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.35/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.36/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.37/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.38/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.39/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.40/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.41/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.42/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.43/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.44/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.45/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.46/view2_tpc2.npz",
    # "pnsNeutrons_output_sim_file_69883239.47/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.48/view2_tpc2.npz",
    "pnsNeutrons_output_sim_file_69883239.49/view2_tpc2.npz",
  ]
  normalized:     False
  root:           "."
  skip_processing:  False
  transform:      null
  pre_transform:  null
  pre_filter:     null

  # ---- variables ----
  positions:  ["channel", "tdc"]
  features:   ["adc"]
  classes:    ["particle"]
  labels:     [
    ["capture_gamma", 
    "capture_gamma_474", 
    "capture_gamma_336",
    "capture_gamma_256",
    "capture_gamma_118",
    "capture_gamma_083",
    "capture_gamma_051",
    "capture_gamma_016",
    "capture_gamma_other",
    "ar39",
    "ar42",
    "kr85",
    "rn222",
    "nuclear_recoil",
    "electron_recoil"]
  ]
  clusters:   ["particle"]

  # ---- normalization ----
  position_normalization:   []
  features_normalization:   []

  # ---- weights ----
  class_weights:  []
  sample_weights: []

  # clustering related parameters
  dbscan_min_samples: 6
  dbscan_eps:         39.0
  cluster_positions:  ["channel", "tdc"]

  # We only want to cluster shapes which are blips
  classes_mask: ["shape"]
  labels_mask:  [["blip"]]
  consolidate_classes:

loader:
  batch_size:       1
  test_split:       0.1
  test_seed:        100
  validation_split: 0.2
  validation_seed:  101
  num_workers:      4
  sparse:           True

training:
  epochs:       25
  checkpoint:   10
  progress_bar: 'all'   # train, validation, test, all
  rewrite_bar:  False   # wether to leave bars after each epoch
  save_predictions: True  # wether to save network outputs in original file
  no_timing:  False     # wether to keep timing/memory info in callback
  seed:       42

model:
  model_type:       "single"
  SparseUResNet:  
    in_channels:      1
    classifications:  ["particle"]               # {"source", "shape", "particle"}
    out_channels:     [15]                     # {8, 7, 32}
    filtrations:      [64, 128, 256, 512]     # the number of filters in each downsample
    double_conv_params:
      kernel_size:  3
      stride:       1
      dilation:     1
      activation:   "relu"
      dimension:    2
      batch_norm:   True
    conv_transpose_params:
      kernel_size:  2
      stride:       2
      dilation:     1
      dimension:    2
    max_pooling_params:
      kernel_size:  2
      stride:       2
      dilation:     1
      dimension:    2

criterion:
  MultiClassCrossEntropyLoss:
    alpha:  1.0
    classes:  ["particle"]
    
metrics:
  ConfusionMatrixMetric:
    mode:   "cluster"
    inputs: ["particle"]
    number_of_classes: [15]
    consolidate_classes:

callbacks:
  LossCallback:
  ConfusionMatrixCallback:
    sig_acceptance: [0.1, 0.5, 0.9]

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9