# Test config file for Blip
module:
  module_name:  'prep_data'
  module_type:  ['dataset']
  module_mode:  ['dataset_prep']
  gpu:          True
  gpu_device:   0
  verbose:      True

dataset:
  skip_processing:  false
  skip_undefined:   true
  transform:        null
  pre_transform:    null
  pre_filter:       null
  dataset_type:   "tpc_cluster"
  dataset_folder: "/local_data/"
  dataset_files:  "all"
  variables:
    positions:      ['x', 'y', 'z']
    features:       []
    classes:        ['particle', 'topology', 'physics_micro', 'physics_meso']
    labels:         []
    clusters:       ['particle', 'topology', 'physics_micro', 'physics_meso']
    hits:           []
    merge_tree:     false
    position_normalization:   []
    features_normalization:   []
    classes_mask: ["topology"]
    labels_mask:  [["blip"]]
    voxelization: [1, 1, 1]

  weights:
    class_weights:  ['particle', 'topology', 'physics_micro', 'physics_meso']
    sample_weights: False
  
  clustering:
    cluster_method:     "physics_meso"
    cluster_positions:  ['x', 'y', 'z']
    cluster_category_type:  "classification" 
    normalize_cluster:  true
    make_gifs:          true