module:
  module_name:  'optimize_blip_graph'
  module_type:  ['ml']
  module_mode:  ['hyper_parameter_scan']
  gpu:          True
  gpu_device:   0
  verbose:      False

dataset:
  process_simulation: False
  simulation_type:    'LArSoft'
  simulation_folder:  ""
  simulation_files:   []

  # ---- Blip ----
  dataset_type:   "view_cluster"
  dataset_folder: "/workspace/data/"
  dataset_files:  [
    "single_capture_gamma_4.745.1/tpc2.npz",
    "single_capture_gamma_4.745.2/tpc2.npz",
    "single_capture_gamma_4.745.3/tpc2.npz",
    "single_capture_gamma_4.745.4/tpc2.npz",
    "single_capture_gamma_4.745.5/tpc2.npz",
    "single_capture_gamma_4.745.6/tpc2.npz",
    "single_capture_gamma_4.745.7/tpc2.npz",
    "single_capture_gamma_4.745.8/tpc2.npz",
    "single_capture_gamma_4.745.9/tpc2.npz",
    "single_capture_gamma_3.3655.0/tpc2.npz",
    "single_capture_gamma_3.3655.1/tpc2.npz",
    "single_capture_gamma_3.3655.2/tpc2.npz",
    "single_capture_gamma_3.3655.3/tpc2.npz",
    "single_capture_gamma_3.3655.4/tpc2.npz",
    "single_capture_gamma_3.3655.5/tpc2.npz",
    "single_capture_gamma_3.3655.6/tpc2.npz",
    "single_capture_gamma_3.3655.7/tpc2.npz",
    "single_capture_gamma_3.3655.8/tpc2.npz",
    "single_capture_gamma_3.3655.9/tpc2.npz",
    "single_capture_gamma_2.5661.0/tpc2.npz",
    "single_capture_gamma_2.5661.1/tpc2.npz",
    "single_capture_gamma_2.5661.2/tpc2.npz",
    "single_capture_gamma_2.5661.3/tpc2.npz",
    "single_capture_gamma_2.5661.4/tpc2.npz",
    "single_capture_gamma_2.5661.5/tpc2.npz",
    "single_capture_gamma_2.5661.6/tpc2.npz",
    "single_capture_gamma_2.5661.7/tpc2.npz",
    "single_capture_gamma_2.5661.8/tpc2.npz",
    "single_capture_gamma_2.5661.9/tpc2.npz",
    "single_capture_gamma_1.1868.0/tpc2.npz",
    "single_capture_gamma_1.1868.1/tpc2.npz",
    "single_capture_gamma_1.1868.2/tpc2.npz",
    "single_capture_gamma_1.1868.3/tpc2.npz",
    "single_capture_gamma_1.1868.4/tpc2.npz",
    "single_capture_gamma_1.1868.5/tpc2.npz",
    "single_capture_gamma_1.1868.6/tpc2.npz",
    "single_capture_gamma_1.1868.7/tpc2.npz",
    "single_capture_gamma_1.1868.8/tpc2.npz",
    "single_capture_gamma_1.1868.9/tpc2.npz",
    "single_capture_gamma_0.8378.0/tpc2.npz",
    "single_capture_gamma_0.8378.1/tpc2.npz",
    "single_capture_gamma_0.8378.2/tpc2.npz",
    "single_capture_gamma_0.8378.3/tpc2.npz",
    "single_capture_gamma_0.8378.4/tpc2.npz",
    "single_capture_gamma_0.8378.5/tpc2.npz",
    "single_capture_gamma_0.8378.6/tpc2.npz",
    "single_capture_gamma_0.8378.7/tpc2.npz",
    "single_capture_gamma_0.8378.8/tpc2.npz",
    "single_capture_gamma_0.8378.9/tpc2.npz",
    "single_capture_gamma_0.516.0/tpc2.npz",
    "single_capture_gamma_0.516.1/tpc2.npz",
    "single_capture_gamma_0.516.2/tpc2.npz",
    "single_capture_gamma_0.516.3/tpc2.npz",
    "single_capture_gamma_0.516.4/tpc2.npz",
    "single_capture_gamma_0.516.5/tpc2.npz",
    "single_capture_gamma_0.516.6/tpc2.npz",
    "single_capture_gamma_0.516.7/tpc2.npz",
    "single_capture_gamma_0.516.8/tpc2.npz",
    "single_capture_gamma_0.516.9/tpc2.npz",
    "single_capture_gamma_0.1673.0/tpc2.npz",
    "single_capture_gamma_0.1673.1/tpc2.npz",
    "single_capture_gamma_0.1673.2/tpc2.npz",
    "single_capture_gamma_0.1673.3/tpc2.npz",
    "single_capture_gamma_0.1673.4/tpc2.npz",
    "single_capture_gamma_0.1673.5/tpc2.npz",
    "single_capture_gamma_0.1673.6/tpc2.npz",
    "single_capture_gamma_0.1673.7/tpc2.npz",
    "single_capture_gamma_0.1673.8/tpc2.npz",
    "single_capture_gamma_0.1673.9/tpc2.npz",
    "single_decay_ar39.0/tpc2.npz",
    "single_decay_ar42.0/tpc2.npz",
  ]
  view:           2
  positions:      ['channel', 'tdc', 'adc']
  features:       ['adc']
  classes:        ['particle', 'physics']
  labels:         []
  clusters:       []
  hits:           []

  root: '.'
  position_normalization:   []
  features_normalization:   []
  class_weights:  []
  sample_weights: []

  dbscan_min_samples: 6
  dbscan_eps:         500.0
  cluster_positions:  ["channel", "tdc"]
  cluster_category_type:  "classification"

  # We only want to cluster shapes which are blips
  classes_mask: ["topology"]
  labels_mask:  [["blip"]]
  skip_processing:  False
  transform:        null
  pre_transform:    null
  pre_filter:       null

loader:
  loader_type:      "minkowski"
  batch_size:       8
  test_split:       0.1
  test_seed:        42
  validation_split: 0.3
  validation_seed:  42
  num_workers:      4

training:
  epochs:       2
  checkpoint:   25
  progress_bar: "all"        # train, validation, test, all
  rewrite_bar:      False # wether to leave bars after each epoch
  save_predictions: True  # wether to save network outputs in original file
  no_timing:    False     # wether to keep timing/memory info in callback
  seed:         0

criterion:
  CrossEntropyLoss:
    alpha:    1.0
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  NTXEntropyLoss:
    alpha:  1.0
    target_type:  "augment_batch"
    targets:  ["reductions"]
    outputs:  ["reductions"]

metrics:
  ConfusionMatrixMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  AdjustedRandIndexMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  AUROCMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  DiceScoreMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  JaccardIndexMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  AveragePrecisionMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  PrecisionMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  RecallMetric:
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5

callbacks:
  LossCallback:
  MetricCallback:
  ConfusionMatrixCallback:

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9