module:
  module_name:  'optimize_blip_graph'
  module_type:  ['ml']
  module_mode:  ['contrastive_training']
  gpu:          true
  gpu_device:   0
  verbose:      true

dataset:
  skip_processing:  false
  transform:        null
  pre_transform:    null
  pre_filter:       null
  view: 2
  dataset_type:   "wire_view_cluster"
  dataset_folder: "/local_data/data/"
  dataset_files:  [
    "single_capture_gamma_4.745.0/tpc2.npz",
    "single_capture_gamma_4.745.1/tpc2.npz",
    "single_capture_gamma_4.745.2/tpc2.npz",
    "single_capture_gamma_4.745.3/tpc2.npz",
    "single_capture_gamma_4.745.4/tpc2.npz",
    "single_capture_gamma_3.365.0/tpc2.npz",
    "single_capture_gamma_3.365.1/tpc2.npz",
    "single_capture_gamma_3.365.2/tpc2.npz",
    "single_capture_gamma_3.365.3/tpc2.npz",
    "single_capture_gamma_3.365.4/tpc2.npz",
    "single_capture_gamma_2.566.0/tpc2.npz",
    "single_capture_gamma_2.566.1/tpc2.npz",
    "single_capture_gamma_2.566.2/tpc2.npz",
    "single_capture_gamma_2.566.3/tpc2.npz",
    "single_capture_gamma_2.566.4/tpc2.npz",
    "single_capture_gamma_1.186.0/tpc2.npz",
    "single_capture_gamma_1.186.1/tpc2.npz",
    "single_capture_gamma_1.186.2/tpc2.npz",
    "single_capture_gamma_1.186.3/tpc2.npz",
    "single_capture_gamma_1.186.4/tpc2.npz",
    "single_capture_gamma_0.837.0/tpc2.npz",
    "single_capture_gamma_0.837.1/tpc2.npz",
    "single_capture_gamma_0.837.2/tpc2.npz",
    "single_capture_gamma_0.837.3/tpc2.npz",
    "single_capture_gamma_0.837.4/tpc2.npz",
    "single_capture_gamma_0.516.0/tpc2.npz",
    "single_capture_gamma_0.516.1/tpc2.npz",
    "single_capture_gamma_0.516.2/tpc2.npz",
    "single_capture_gamma_0.516.3/tpc2.npz",
    "single_capture_gamma_0.516.4/tpc2.npz",
    "single_capture_gamma_0.167.0/tpc2.npz",
    "single_capture_gamma_0.167.1/tpc2.npz",
    "single_capture_gamma_0.167.2/tpc2.npz",
    "single_capture_gamma_0.167.3/tpc2.npz",
    "single_capture_gamma_0.167.4/tpc2.npz",
    "single_decay_ar39.0/tpc2.npz",
    "single_decay_ar39.1/tpc2.npz",
    "single_decay_ar39.2/tpc2.npz",
    "single_decay_ar39.3/tpc2.npz",
    "single_decay_ar39.4/tpc2.npz",
    "single_decay_ar42.0/tpc2.npz",
    "single_decay_ar42.1/tpc2.npz",
    "single_decay_ar42.2/tpc2.npz",
    "single_decay_ar42.3/tpc2.npz",
    "single_decay_ar42.4/tpc2.npz",
    "single_decay_kr85.0/tpc2.npz",
    "single_decay_kr85.1/tpc2.npz",
    "single_decay_kr85.2/tpc2.npz",
    "single_decay_kr85.3/tpc2.npz",
    "single_decay_kr85.4/tpc2.npz",
    "single_decay_rn222.0/tpc2.npz"
  ]
  variables:
    positions:      ['channel', 'tdc', 'adc']
    features:       ['adc']
    classes:        ['particle', 'physics']
    labels:         []
    clusters:       []
    hits:           []
    position_normalization:   []
    features_normalization:   []
    classes_mask: ["topology"]
    labels_mask:  [["blip"]]

  weights:
    class_weights:  []
    sample_weights: False

  clustering:
    dbscan_min_samples: 6
    dbscan_eps:         500.0
    cluster_positions:  ["channel", "tdc"]
    cluster_category_type:  "classification"  

loader:
  loader_type:      "minkowski"
  batch_size:       64
  test_split:       0.1
  test_seed:        42
  validation_split: 0.3
  validation_seed:  42
  num_workers:      4

training:
  iterations:   1
  epochs:       100
  checkpoint:   25
  progress_bar: "all"     # train, validation, test, all
  rewrite_bar:      false # wether to leave bars after each epoch
  save_predictions: false # wether to save network outputs in original file
  no_timing:    true      # wether to keep timing/memory info in callback
  skip_metrics: true      # wether to skip metrics except for testing sets
  seed:         0

linear_evaluation:
  epochs: 25

model_analyzer:
  ContrastiveModelAnalyzer:
    dataset_type: "test"
    layers:       []
    outputs:      ["reductions"]
    perplexities: [5,10,25,50]
    eps_values:   [25,50]

criterion:
  CrossEntropyLoss:
    alpha:    1.0
    target_type:  "classes"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  NTXEntropyLoss:
    alpha:  1.0
    target_type:  "augment_batch"
    targets:  ["projection_head"]
    outputs:  ["projection_head"]

metrics: 
  ConfusionMatrixMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  AdjustedRandIndexMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  AUROCMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  DiceScoreMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  JaccardIndexMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  AveragePrecisionMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  PrecisionMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5
  RecallMetric:
    target_type:  "classes"
    when_to_compute:  "test"
    targets:  ["particle", "physics"]
    outputs:  ["particle", "physics"]  
    augmentations:  5

callbacks:
  LossCallback:
  MetricCallback:
    skip_metrics: true
  ConfusionMatrixCallback:
    skip_metrics: true

optimizer:
  optimizer_type: "Adam"
  learning_rate:  0.01
  betas:          [0.9, 0.999]
  epsilon:        1e-08
  weight_decay:   0.001
  momentum:       0.9