# Test config file for Blip
module:
  module_name:  'prep_data'
  module_type:  ['arrakis']
  module_mode:  ['larsoft_singles']
  gpu:          True
  gpu_device:   0
  verbose:      False

arrakis:
    # ---- Arrakis ----
  # This section defines the 'arrakis.py' submodule which takes in
  # outputs from different Arrakis iterations and constructs a common dataset format
  # in .npz or .hdf5 files.
  simulation_folder:  "/local_data/data/singles/"
  process_type:       ['wire_plane_point_cloud']
  simulation_files:   [
    "prod_pns_capture_gamma_474_5kevt_v3.root"
  ]