# Test config file for Blip
module:
  module_name:  'prep_data'
  module_type:  ['data']
  module_mode:  ['arrakis']
  gpu:          True
  gpu_device:   0
  verbose:      False

dataset:
    # ---- Arrakis ----
  # This section defines the 'arrakis.py' submodule which takes in
  # outputs from different Arrakis iterations and constructs a common dataset format
  # in .npz or .hdf5 files.
  # If this is the first time processing the simulation output
  process_simulation: True
  simulation_type:    'LArSoft'
  simulation_folder:  "/workspace/data/"
  process_type:       ['wire_plane_point_cloud']
  simulation_files:   [
    "single_capture_gamma_4.745.1.root",
    "single_capture_gamma_4.745.2.root",
    "single_capture_gamma_4.745.3.root",
    "single_capture_gamma_4.745.4.root",
    "single_capture_gamma_4.745.5.root",
    "single_capture_gamma_4.745.6.root",
    "single_capture_gamma_4.745.7.root",
    "single_capture_gamma_4.745.8.root",
    "single_capture_gamma_4.745.9.root",
    "single_capture_gamma_3.3655.0.root",
    "single_capture_gamma_3.3655.1.root",
    "single_capture_gamma_3.3655.2.root",
    "single_capture_gamma_3.3655.3.root",
    "single_capture_gamma_3.3655.4.root",
    "single_capture_gamma_3.3655.5.root",
    "single_capture_gamma_3.3655.6.root",
    "single_capture_gamma_3.3655.7.root",
    "single_capture_gamma_3.3655.8.root",
    "single_capture_gamma_3.3655.9.root",
    "single_capture_gamma_2.5661.0.root",
    "single_capture_gamma_2.5661.1.root",
    "single_capture_gamma_2.5661.2.root",
    "single_capture_gamma_2.5661.3.root",
    "single_capture_gamma_2.5661.4.root",
    "single_capture_gamma_2.5661.5.root",
    "single_capture_gamma_2.5661.6.root",
    "single_capture_gamma_2.5661.7.root",
    "single_capture_gamma_2.5661.8.root",
    "single_capture_gamma_2.5661.9.root",
    "single_capture_gamma_1.1868.0.root",
    "single_capture_gamma_1.1868.1.root",
    "single_capture_gamma_1.1868.2.root",
    "single_capture_gamma_1.1868.3.root",
    "single_capture_gamma_1.1868.4.root",
    "single_capture_gamma_1.1868.5.root",
    "single_capture_gamma_1.1868.6.root",
    "single_capture_gamma_1.1868.7.root",
    "single_capture_gamma_1.1868.8.root",
    "single_capture_gamma_1.1868.9.root",
    "single_capture_gamma_0.8378.0.root",
    "single_capture_gamma_0.8378.1.root",
    "single_capture_gamma_0.8378.2.root",
    "single_capture_gamma_0.8378.3.root",
    "single_capture_gamma_0.8378.4.root",
    "single_capture_gamma_0.8378.5.root",
    "single_capture_gamma_0.8378.6.root",
    "single_capture_gamma_0.8378.7.root",
    "single_capture_gamma_0.8378.8.root",
    "single_capture_gamma_0.8378.9.root",
    "single_capture_gamma_0.516.0.root",
    "single_capture_gamma_0.516.1.root",
    "single_capture_gamma_0.516.2.root",
    "single_capture_gamma_0.516.3.root",
    "single_capture_gamma_0.516.4.root",
    "single_capture_gamma_0.516.5.root",
    "single_capture_gamma_0.516.6.root",
    "single_capture_gamma_0.516.7.root",
    "single_capture_gamma_0.516.8.root",
    "single_capture_gamma_0.516.9.root",
    "single_capture_gamma_0.1673.0.root",
    "single_capture_gamma_0.1673.1.root",
    "single_capture_gamma_0.1673.2.root",
    "single_capture_gamma_0.1673.3.root",
    "single_capture_gamma_0.1673.4.root",
    "single_capture_gamma_0.1673.5.root",
    "single_capture_gamma_0.1673.6.root",
    "single_capture_gamma_0.1673.7.root",
    "single_capture_gamma_0.1673.8.root",
    "single_capture_gamma_0.1673.9.root",
    "single_decay_ar39.0.root",
    "single_decay_ar42.0.root"
  ]