load_config: '/workspace/BlipModels/blip_graph/configs/optimize_header.yaml'

hyper_parameters:
  iterations: 1
  search_type:  'grid'  # 'grid', 'random', 'bayes'
  model_parameters:
    BlipGraph:
      embedding:
        embedding_1:
          fps_ratio:      [0.10, 0.25, 0.5, 0.75]
          max_number_neighbors: [5,10,25]
          add_self_loops:       [true, false]
        embedding_2:
          fps_ratio:      [0.10, 0.25, 0.5, 0.75]
          max_number_neighbors: [5,10,25]
          add_self_loops:       [true, false]
        embedding_3:
          fps_ratio:      [0.10, 0.25, 0.5, 0.75]
          max_number_neighbors: [5,10,25]
          add_self_loops:       [true, false]

model:
  model_type:       "single"  
  BlipGraph:
    input_dimension:      3
    classifications:      ["particle", "physics"]
    add_summed_adc:       true
    augmentations:
      jitter: 0.03
      flip:
        positions:     [0, 1]
        probabilities: [0.5, 0.5]
      shear:  0.2
      rotate:
        degrees:  [15]
        axis:     [2]
      number_of_augmentations:  5
    embedding:
      embedding_1:  
        embedding_type:   'point_net_conv'
        local_mlp_layers: [10, 25, 50]
        fps_ratio:        0.5
        cluster_radius:   0.25
        max_number_neighbors: 5
        add_self_loops:   true
      embedding_2:  
        embedding_type:   'point_net_conv'
        local_mlp_layers: [10, 25, 50]
        fps_ratio:        0.5
        cluster_radius:   0.25
        max_number_neighbors: 5
        add_self_loops:   true
      embedding_3:  
        embedding_type:   'point_net_conv'
        local_mlp_layers: [10, 25, 50]
        fps_ratio:        0.5
        cluster_radius:   0.25
        max_number_neighbors: 5
        add_self_loops:   true
    reduction:
      reduction_type: 'max_pool'
      linear_output:  512
    classification:
      mlp_output_layers:    [512, 256, 128, 64, 32]
      out_channels:         [28, 39]