# Test config file for Blip
module:
  module_name:  'prep_data'
  module_type:  ['dataset']
  module_mode:  ['dataset_prep']
  gpu:          True
  gpu_device:   0
  verbose:      True

dataset:
  skip_processing:  false
  skip_undefined:   true
  transform:        null
  pre_transform:    null
  pre_filter:       null
  dataset_type:   "tpc"
  dataset_folder: "/local_data/"
  dataset_files:  [
    "MiniRun4_1E19_RHC.flow.00000.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00001.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00002.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00003.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00004.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00005.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00006.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00007.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00008.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00009.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00010.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00011.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00012.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00013.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00014.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00015.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00016.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00017.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00018.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00019.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00020.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00021.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00022.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00023.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00024.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00025.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00026.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00027.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00028.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00029.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00030.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00031.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00032.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00033.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00034.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00035.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00036.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00037.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00038.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00039.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00040.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00041.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00042.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00043.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00044.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00045.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00046.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00047.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00048.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00049.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00050.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00051.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00052.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00053.FLOW.arrakis_nd.npz",
    "MiniRun4_1E19_RHC.flow.00054.FLOW.arrakis_nd.npz"
  ]
  variables:
    positions:      ['x', 'y', 'z']
    features:       []
    classes:        ['particle', 'topology', 'physics_micro', 'physics_meso', 'physics_macro']
    labels:         []
    clusters:       []
    hits:           []
    position_normalization:   []
    features_normalization:   []
    classes_mask: []
    labels_mask:  [[]]
    voxelization: [1, 1, 1]

  weights:
    class_weights:  []
    sample_weights: False