load_config: '/workspace/BlipModels/blip_graph/configs/optimize_header.yaml'

hyper_parameters:
  iterations: 10
  search_type:  'grid'  # 'grid', 'random', 'bayes'
  model_parameters:
    BlipGraph:
      embedding:
        embedding_1:
          number_of_neighbors:  [5, 10, 20]
          aggregation:          ['max', 'mean', 'sum']
          embedding_mlp: 
            layers: [[5,10,25,10],[10,25,50,25],[25,50,100,25]]
            dropout:  [0.1,0.01,0.05]

model:
  model_type:       "single"  
  BlipGraph:
    input_dimension:      3
    classifications:      ["particle", "physics"]
    add_summed_adc:       false
    augmentations:
      jitter: 0.03
      flip:
        positions:     [0, 1]
        probabilities: [0.5, 0.5]
      shear:  0.2
      rotate:
        degrees:  [15]
        axis:     [2]
      number_of_augmentations:  5
    embedding:
      embedding_1:  
        embedding_type: 'dynamic_edge_conv'
        number_of_neighbors:  5
        aggregation:    'max'
        embedding_mlp:
          layers: [5, 10, 25, 10]
          dropout:  0.1
          activation: 'LeakyReLU'
          activation_params:
            negative_slope: 0.1
    reduction:
      reduction_type: 'max_pool'
      linear_output:  512
      projection_head_layers:   [512, 1024, 512, 256]
      projection_head_dropout:  0.1
      projection_head_activation:  'LeakyReLU'
      projection_head_activation_params:
        negative_slope: 0.1
    classification:
      mlp_output_layers:    [256, 128, 64, 32]
      out_channels:         [28, 39]
      dropout:  0.1
      activation: 'LeakyReLU'
      activation_params:
        negative_slope: 0.1