load_config: '/workspace/BlipModels/blip_graph/configs/optimize_header.yaml'

hyper_parameters:
  iterations: 25
  search_type:  'grid'  # 'grid', 'random', 'bayes'
  model_parameters:
    BlipGraph:
      embedding:
        embedding_1:
          number_of_neighbors:  [5, 10, 20]
          aggregation:          ['max', 'mean', 'sum']
          embedding_mlp_layers: [[5,10,25,10],[10,25,50,25],[25,50,100,25]]
        embedding_2:
          number_of_neighbors:  [5, 10, 20]
          aggregation:          ['max', 'mean', 'sum']
          embedding_mlp_layers: [[5,10,25,10],[10,25,50,25],[25,50,100,25]]

model:
  model_type:       "single"  
  BlipGraph:
    input_dimension:      3
    classifications:      ["particle", "physics"]
    add_summed_adc:       false
    augmentations:
      jitter: 0.03
      flip:
        positions:     [0, 1]
        probabilities: [0.5, 0.5]
      shear:  0.2
      rotate:
        degrees:  [15]
        axis:     [2]
      number_of_augmentations:  5
    embedding:
      embedding_1:  
        embedding_type: 'dynamic_edge_conv'
        number_of_neighbors:  5
        aggregation:    'max'
        embedding_mlp_layers: [5, 10, 25, 10]
      embedding_2:  
        embedding_type: 'dynamic_edge_conv'
        number_of_neighbors:  5
        aggregation:    'max'
        embedding_mlp_layers: [5, 10, 25, 10]
    reduction:
      reduction_type: 'max_pool'
      linear_output:  512
      projection_head:  [512, 1024, 512, 256]
    classification:
      mlp_output_layers:    [256, 128, 64, 32]
      out_channels:         [28, 39]