# Test config file for Blip
module:
  module_name:  'pion_analysis_LM'
  # module_type:  ['PionAnalysisModule']
  # module_mode:  ['analysis']
  module_type:  ['data']
  module_mode:  ['arrakis']
  custom_module_file: "/home/laura/Analysis_Laura/BlipModels/pion/pion_analysis.py"
  gpu:          True
  gpu_device:   0
  verbose:      True

dataset:
  # If this is the first time processing the simulation output
  process_simulation: True
  simulation_type:    'LArSoft'
  simulation_folder:  "/home/laura/Analysis_Laura/BlipModels/pion/data/"
  process_type: ["wire_plane_point_cloud"]
  simulation_files:   [
    "piplus1GeV_output_sim_file_2349667.0.root",
    "piplus1GeV_output_sim_file_2349667.1.root"
  ]

  # # Otherwise, we want to just load the resulting data
  # dataset_type:   "voxel"
  # dataset_folder: "/home/laura/Analysis_Laura/BlipModels/pion/data/"
  # dataset_files:  [
  #   "piplus1GeV_output_sim_file_2349667.8/view2_tpc2.npz",
  #   "piplus1GeV_output_sim_file_2349667.9/view2_tpc2.npz"
  # ]
  # normalized:     False
  # root:           "."
  # skip_processing:  False
  # transform:      null
  # pre_transform:  null
  # pre_filter:     null

  # # ---- variables ----
  # positions:  ["channel", "tdc", "adc"]
  # features:   ["adc"]
  # classes:    ["particle"]
  # labels:     [
  #   [
  #     "pi+"
  #   ]
  # ]
  # clusters:   ["particle"]

  # # ---- normalization ----
  # position_normalization:   []
  # features_normalization:   []

  # # ---- weights ----
  # class_weights:  []
  # sample_weights: []

  # # clustering related parameters
  # dbscan_min_samples: 6
  # dbscan_eps:         500.0
  # cluster_positions:  ["channel", "tdc"]
  # cluster_category_type:  "classification"

  # # We only want to cluster shapes which are blips
  # classes_mask: []
  # labels_mask:  []
  # consolidate_classes:

loader:
  batch_size:       8
  test_split:       0.1
  test_seed:        100
  validation_split: 0.2
  validation_seed:  101
  num_workers:      4
  sparse:           True